title: 사무실에서 적는 일기
author: ㅅㅇㄱ
subtitle: 지옥에서 절망중인 개발자의 사업로그

url: "https://veduardovich.github.io/"
baseurl: ""

footer_only_homepage: true
footer_url: "https://veduardovich.github.io/"
footer_text: "지옥에서 절망중인 개발자의 사업로그"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
#  - name: "Resume"
#    absolute-link: "https://rahul-bothra.github.io/CV.pdf"
